/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LauchQuiz {
    'questions': { question: string; answers: { label: string; value: string; }[]; }[];
    'results': { label: string; value: string; }[];
  }
}

declare global {


  interface HTMLLauchQuizElement extends Components.LauchQuiz, HTMLStencilElement {}
  var HTMLLauchQuizElement: {
    prototype: HTMLLauchQuizElement;
    new (): HTMLLauchQuizElement;
  };
  interface HTMLElementTagNameMap {
    'lauch-quiz': HTMLLauchQuizElement;
  }
}

declare namespace LocalJSX {
  interface LauchQuiz {
    'questions'?: { question: string; answers: { label: string; value: string; }[]; }[];
    'results'?: { label: string; value: string; }[];
  }

  interface IntrinsicElements {
    'lauch-quiz': LauchQuiz;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lauch-quiz': LocalJSX.LauchQuiz & JSXBase.HTMLAttributes<HTMLLauchQuizElement>;
    }
  }
}


